import { Glyph } from '@/components/chrome/Wordmark'
import { GlassPanel } from '@/components/ui/GlassPanel'
import { Hud, Rule } from '@/components/ui/Hud'
import { Reveal } from '@/components/ui/Reveal'
import { useApp } from '@/store/useApp'

/**
 * The honesty ledger. Rather than burying caveats in tooltips, the page ends
 * with a single place that states, line by line, what is real in this build
 * and what is a stand-in. A judge should be able to read this and know
 * exactly what they are looking at.
 */
const LEDGER = [
  {
    k: 'Scoring math',
    v: 'Real',
    note: 'Cosine reversal, WTCS, score fusion and the recovery check are ported line-for-line from the Python pipeline and run live in this page.',
    accent: 'text-mint',
  },
  {
    k: 'Disease signature',
    v: 'Synthetic',
    note: 'Generated by the repository’s mock-data script. A real RA signature from GEO drops into the same three columns with no code change.',
    accent: 'text-amber',
  },
  {
    k: 'Compound library',
    v: 'Synthetic',
    note: 'Placeholder identifiers with a planted reversal signal. Not real compounds and not real LINCS L1000 profiles.',
    accent: 'text-amber',
  },
  {
    k: 'Safety screen',
    v: 'Standby',
    note: 'Lipinski Rule of Five is implemented but inactive — it needs a structure descriptor table, so a neutral 0.50 is used instead of a guess.',
    accent: 'text-amber',
  },
  {
    k: 'Pathway enrichment',
    v: 'Standby',
    note: 'Requires the Enrichr API and real HGNC symbols. Neither is available against a synthetic benchmark.',
    accent: 'text-amber',
  },
  {
    k: 'Clinical evidence',
    v: 'None',
    note: 'Nothing on this page is a clinical finding, an experimental result, or a claim about any real drug.',
    accent: 'text-ember',
  },
]

export function Footer() {
  const result = useApp((s) => s.result)

  return (
    <footer className="relative px-5 pb-16 pt-20 sm:px-8">
      <div className="mx-auto w-full max-w-[1400px]">
        <Rule className="mb-16" />

        <Reveal>
          <div className="mb-10 flex flex-wrap items-end justify-between gap-6">
            <div>
              <Hud className="mb-3 block text-mint">Honesty ledger</Hud>
              <h2 className="max-w-xl font-display text-[26px] font-semibold leading-tight tracking-[-0.03em] sm:text-[32px]">
                What is real in this build, and what is a stand-in.
              </h2>
            </div>
            {result && (
              <div className="text-right">
                <Hud className="block">Last run</Hud>
                <p className="num mt-1.5 text-[12px] text-dim">
                  {result.methodLabel} · {Object.values(result.timings).reduce((a, b) => a + b, 0).toFixed(1)} ms total compute
                </p>
              </div>
            )}
          </div>
        </Reveal>

        <Reveal delay={0.05}>
          <GlassPanel kind="primary" className="overflow-hidden">
            <ul>
              {LEDGER.map((row) => (
                <li
                  key={row.k}
                  className="grid gap-2 border-b border-line/[0.07] px-5 py-4 last:border-0 sm:grid-cols-[190px_100px_minmax(0,1fr)] sm:items-baseline sm:gap-5 sm:px-7"
                >
                  <span className="font-display text-[13.5px] font-medium text-ink">{row.k}</span>
                  <span
                    className={`font-mono text-[10px] font-semibold uppercase tracking-hud ${row.accent}`}
                  >
                    {row.v}
                  </span>
                  <span className="text-[12px] leading-relaxed text-dim text-pretty">
                    {row.note}
                  </span>
                </li>
              ))}
            </ul>
          </GlassPanel>
        </Reveal>

        <Reveal delay={0.1}>
          <div className="mt-14 flex flex-wrap items-end justify-between gap-8 border-t border-line/10 pt-8">
            <div className="flex items-center gap-3">
              <Glyph size={30} />
              <div>
                <div className="font-display text-[15px] font-semibold tracking-[-0.03em]">
                  <span className="text-ink">Repurpose</span>
                  <span className="text-mint">AI</span>
                </div>
                <Hud className="mt-1 block">Computational drug repurposing</Hud>
              </div>
            </div>

            <div className="flex flex-wrap gap-x-10 gap-y-3">
              <FooterMeta k="Target" v="Rheumatoid arthritis" />
              <FooterMeta k="Runtime" v="In-page, offline capable" />
              <FooterMeta k="Backend" v="Adapter-ready" />
            </div>
          </div>
        </Reveal>
      </div>
    </footer>
  )
}

function FooterMeta({ k, v }: { k: string; v: string }) {
  return (
    <div>
      <Hud className="block">{k}</Hud>
      <div className="mt-1.5 text-[12.5px] text-dim">{v}</div>
    </div>
  )
}
